Dnsdock:
 image: tonistiigi/dnsdock
 hostname: dnsdock
 #restart: always
 ports:
#   - 8080:80
   - 172.17.0.1:53:53/udp
 volumes:
   - /var/run/docker.sock:/var/run/docker.sock

mysql:
  build: mysql/
  environment:
    MYSQL_USER: admin
    MYSQL_PASS: DgGz6fnp
    STARTUP_SQL: /tmp/init/*.sql
  ports:
    - 3306:3306
#  volumes:
#    - /data/mysql:/var/lib/mysql

mongodb:
  build: mongodb/
#  volumes:
#    - /data/mongodb:/data/db
  ports:
    - 27017:27017
  command: mongod --smallfiles


sla:
  build: sla-core/
  links:
    - mysql
  dns:
    - 172.17.0.1
  ports:
    - 9040:9040
  environment:
    - DNSDOCK_ALIAS=sla.docker


dashboard:
  build: dashboard/

vnfs:
  build: vnfs/
  links:
    - mongodb
  ports:
    - 5000:5000
  dns:
    - 172.17.0.1
  environment:
    - DNSDOCK_ALIAS=vnfs.docker
    - NFS_HOST=172.16.0.20
    - NFS_PORT=8080
    - SECRET_KEY=^9xi7kyli7-43r(m5b5ykl5uq@61kuk-4zyd$c2q-o&ma&gllo
    - DOCKER_HOST=https://5gex.tmit.bme.hu
    - DOCKER_AUTH_EP=auth
    - DOCKER_REPO_EP=v2
    - DOCKER_SERVICE=registry.5gex
    - DOCKER_USER=fgxdev
    - DOCKER_PASS=5GEXhack3r29
    - DOMAIN_ID=001


mdc:
  build: mdc/
  links:
    - mysql
  ports:
    - 8500:8500
  dns:
    - 172.17.0.1
  environment:
    - DNSDOCK_ALIAS=mdc.docker
    - NFS_HOST=172.16.0.20
    - NFS_PORT=8080
    - NFS_VNFD_EP=:8080/NFS/vnfds
    - NFS_VNFD_URL=http://172.16.0.20:8080/NFS/vnfds
    - MDC_EP=:8500/mdc/
    - MDC_PORT=8500
    - BSC_EP=/service-catalog/service/catalog
    - BSC_URL=http://172.16.0.20:42050/service/catalog
    - DOMAIN_ID=001
    - ENTRY_POINT=http://172.16.0.20
    - DOCKER_ENV=True


servicecatalog:
  build: service-catalog/
  links:
    - mongodb
  dns:
    - 172.17.0.1
  ports:
    - 42050:42050
  environment:
    - DNSDOCK_ALIAS=bsc.docker,service-catalog.docker
    - MONGO_HOST=mongodb
    - MONGO_PORT=27017
    - CONNECTOR_IP=172.16.0.10
    - CONNECTOR_PORT=9000
    - CONNECTOR_HOST=http://172.16.0.10:9000/nsd
    - MDC_HOST=http://mdc.docker:8500/mdc/
    - SLA_HOST=http://sla.docker:9040/templates


serviceselection:
  build: service-selection/
  links:
    - mongodb
  dns:
    - 172.17.0.1
  ports:
    - 42055:42055
  environment:
    - DNSDOCK_ALIAS=service-selection.docker
    - CONNECTOR_IP=172.16.0.10
    - CONNECTOR_PORT=9000
    - CONNECTOR_HOST=http://172.16.0.20:9000
    - CONNECTOR_INSTANTIATION_URL=http://172.16.0.20:9000/service
    - CONNECTOR_INSTANCES_URL=http://172.16.0.20:9000/ns-instances
    - ACCOUNTING_HOST=http://accounting.docker:8000/accounts/
    - BSC_HOST=http://bsc.docker:42050/service/catalog
    - VNFS_HOST=http://vnfs.docker:5000/internal/vnfs
    - CALLBACK_URL=http://172.16.0.20:42055/service-selection/service/selection/



#billing:
#  build: cyclops/docker-files/cyclops-aio
#  privileged: true
#  # need to link them because of the dns ipv4 resolve problem
#  links:
#    - accounting
#  cap_add:
#    - SYS_PTRACE
#  dns:
#    - 172.17.0.1
#  ports:
#    - 8080:8080
#    - 8083:8083
#    - 8086:8086
#  environment:
#    - DNSDOCK_ALIAS=cyclops.docker

accounting:
  build: accounting/
  links:
    - mysql
  ports:
    - 8000:8000
  dns:
    - 172.17.0.1
  environment:
    - DNSDOCK_ALIAS=accounting.docker
    - AMQP_HOST=10.10.1.226
    - AMQP_PORT=5672
    - IMOS_URL=http://imos:2222/monitoring/?serviceid=

umaa:
  build: umaa/
  links:
    - mysql
  dns:
    - 172.17.0.1
  environment:
    - DNSDOCK_ALIAS=umaa.docker
    - SECRET_KEY=^9xi7kyli7-43r(m5b5ykl5uq@61kuk-4zyd$c2q-o&ma&gllo
    - DOMAIN_ID=ATOS

proxy:
  build: proxy/
  links:
    - umaa
    - vnfs
#    - broker
#    - billing
    - accounting
    - mdc 
    - sla
    - servicecatalog
    - serviceselection
    - dashboard
  ports:
    - 80:80
  dns:
    - 172.17.0.1
  environment:
    - DNSDOCK_ALIAS=proxy.docker,web.docker
    - NFS_URL=http://172.16.0.10:8080
    - BILLING_URL=http://172.16.6.85:8080
    - ORCHESTRATOR_URL=http://172.16.0.10:9000
    - CONNECTOR_URL=http://172.16.0.20:5000
